apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: getting-started
  namespace: tutorial
spec:
  storageClassName: "nfs-client"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
